try {
    let a=5;
    a.toUppercase()
} catch (error) {
    console.log(error)
}